#!/bin/bash


gn_url="https://chrome-infra-packages.appspot.com/dl/gn/gn/windows-amd64/+/latest"
#https://chrome-infra-packages.appspot.com/p/gn/gn/windows-amd64/+/latest

_docmd() {
	echo
	printf 'Download gn from CIPD Packages..'
	wget -c -q "${gn_url}" -O gn.zip
	[ -d bin ] || mkdir bin
	unzip gn.zip gn.exe -d bin >/dev/null
	rm gn.zip
	printf 'done.\n'

	printf 'Download the latest version of Ninja from GitHub...'
	wget -c -q https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip
	unzip ninja-win.zip ninja.exe -d bin >/dev/null
	rm ninja-win.zip
	printf 'done.\n'

	chmod 755 bin/{gn,ninja}.exe
}

_docmd
