#!/bin/bash

ver="$(<VERSION)"
SRCDEST="/c/chromium_sources_$ver"

export PATH="$PWD/bin":$PATH
export DEPOT_TOOLS_WIN_TOOLCHAIN=0
export vs2022_install="C:\Program Files\Microsoft Visual Studio\2022\Enterprise"


_runhooks() {
	echo 'RunHooks...'
	python3 src/tools/clang/scripts/update.py
	wget -c -nv "https://commondatastorage.googleapis.com/chromium-browser-clang/rc/$(cat src/build/toolchain/win/rc/win/rc.exe.sha1)" \
	-O src/build/toolchain/win/rc/win/rc.exe

	#wget -c -nv "https://gnuwin32.sourceforge.net/downlinks/gperf-bin-zip.php" -O gperf-bin.zip #wget -c -nv "https://gnuwin32.sourceforge.net/downlinks/gperf-src-zip.php" -O gperf-src.zip
	git clone --depth=1 "https://chromium.googlesource.com/chromium/deps/gperf" src/third_party/gperf

	wget -c -nv "https://chrome-infra-packages.appspot.com/dl/infra/3pp/tools/7z/windows-amd64/+/latest" -O lzma-sdk-win64.zip
	unzip lzma-sdk-win64.zip 7z* -d src/third_party/lzma_sdk/bin/win64
	cp src/third_party/lzma_sdk/bin/win64/7z* -t src/third_party/lzma_sdk/bin/host_platform
	rm -f lzma-sdk-win64.zip

	node_ver="$(curl -sL https://github.com/ywzgt/chrome-bld-git/raw/main/version_node)" || node_ver='v18.16.0'
	wget -nv -c "https://nodejs.org/dist/${node_ver}/win-x64/node.exe" -P "src/third_party/node/win"
	src/third_party/node/win/node.exe --version

	_node_with_npmModules() {
		wget -nv -c "https://nodejs.org/dist/${node_ver}/node-${node_ver}-win-x64.7z"
		bsdtar xf "node-${node_ver}-win-x64.7z" --strip-components=1 -C src/third_party/node/win/
		rm "node-${node_ver}-win-x64.7z"
	}
}

_docmd() {
	cd "${SRCDEST}"
	_runhooks
	echo; df -Tha
}

_docmd
