#!/bin/bash


ver="$(<VERSION)"
build_dir="src/out/android"
export NINJA_STATUS="[%r %f/%t %es] "
export PATH="$PWD/bin":$PATH
export REBASELINE_PROGUARD=1

_docmd() {
	local targets=(
		#trichrome_chrome_bundle  # only bundle
		#trichrome_library_apk  # only apk
		#trichrome_webview_apk  # or bundle
		system_webview_apk
		chrome_public_apk
	)

	#ninja -C "${build_dir}" components/content_settings/core/common:bromite_content_settings
	#components/page_image_service/mojom:mojo_bindings \
	#	chrome/browser/resource_coordinator:mojo_bindings page_info_buildflags

	sed '/^chrome_public_manifest_package/c\chrome_public_manifest_package = "org.chromium.chrome"' -i "${build_dir}/args.gn"
	ninja -C "${build_dir}" chrome_public_{apk,bundle} monochrome_public_bundle || _exit # echo ":: Build failed!"
}

_exit() {
	local a=$?
	if pidof -q sleep; then
		return $a
	else
		return 0
	fi
}

sleep 18000 && pkill ninja &
_docmd
