#!/bin/bash

ver="$(<VERSION)"
SRCDEST="/c/chromium_sources_$ver"
build_dir="src/out/win64"
GIT_DIR="$PWD"

_pack() {
	mkdir -v "build-$ver"

	pushd "${SRCDEST}/src" >/dev/null 2>&1
	printf ':: Package the builded cache as tar, Using xz Compression...'
	tar cf - out|xz -T0 > "${GIT_DIR}/build-$ver/$ver.bld.tar.xz"
	printf 'done.\n'

	cd "${GIT_DIR}/build-$ver"
	printf "Print information for file '$ver.bld.tar.xz' to file.list..."
	file $ver.bld.tar.xz >file.list
	ls -lh $ver.bld.tar.xz >>file.list
	ls -l $ver.bld.tar.xz >>file.list
	tar tvf $ver.bld.tar.xz|head -5000 >>file.list
	printf 'done.\n\n'

	du -sh $ver.bld.tar.xz
	echo
	split -d -b 49m $ver.bld.tar.xz $ver.bld.part.tar.xz. --verbose
	sha512sum $ver.bld.* >sha512
	rm $ver.bld.tar.xz
	popd >/dev/null 2>&1

	exit 0
}

_docmd() {
	cp "${SRCDEST}/${build_dir}"/mini_installer.exe . || _pack
	echo 'Compile chromium complete.'
	ls -l *.exe
	file *.exe
	touch PUSH_CHROMIUM_${ver}_EXE
}

_docmd
